### ISSUE TITLE
Listing multiple packages in the same \usepackage{...} command

### ISSUE THREAD

**Issue by j-griffiths** [arxiv-vanity/engrafo#1013]
Unsure if this is a general issue, or if it is specific to `pgfplotstable`. I have two LaTeX packages imported in the same line in the preamble:

```
\usepackage{pgfplots,pgfplotstable}
```

which returns the error for a tikz figure in the main body of the LaTeX

```
Error:latex:\GenericError Package pgfplotstable Error: Please load \usepackage{pgfplotstable} before using \pgfplotstablecreatecol
	at main.tex; line 759 col 0 - line 759 col 64
	See the pgfplotstable package documentation for explanation.
	In Core::Definition::Primitive[\GenericE... /usr/local/share/perl/5.30.0/LaTeXML/Package/LaTeX.pool.ltxml; line 5070
	 <= Core::Stomach[@0x55635732e570] <= Core::Definition::Primitive[Begin] <= Core::Stomach[@0x55635732e570] <= ...
```

Can you confirm if multiple packages can be listed in the same command? If not, could this be implemented?

JG

**Comment by bfirsh** [comment]
Hmm -- interesting. If this works in normal TeX, sounds like LaTeXML loads multiple packages on a single line in a different order, or something like that. This is an upstream issue in LaTeXML, so might be worth filing an issue there to see what they think: https://github.com/brucemiller/LaTeXML

**Comment by j-griffiths** [comment]
Issue filed with LaTeXML—not a TeX issue.

See issue https://github.com/brucemiller/LaTeXML/issues/1304

**Comment by j-griffiths** [comment]
This is an issue with LaTeXML—it does not include this pgf binding. I have logged the issue over there https://github.com/brucemiller/LaTeXML/issues/1304 and will close this issue.
