### ISSUE TITLE
script/arxiv-dev-server: error Command "server" not found. Did you mean "semver"?

### ISSUE THREAD

**Issue by turian** [arxiv-vanity/engrafo#1078]
I try to run the instructions in the README in a local docker.

However, I get

```
# script/arxiv-dev-server 1707.08901
yarn run v1.22.4
error Command "server" not found. Did you mean "semver"?
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by bfirsh** [comment]
I've had a go at fixing this blind -- does this work now?

https://github.com/arxiv-vanity/engrafo/commit/2ac87e215daea32699aa7f888f0405936d2ef452

**Comment by turian** [comment]
I am now having trouble building the docker which is blocking me from testing this: https://github.com/arxiv-vanity/engrafo/issues/1079

Is there a simple command I can use a prebuilt docker and try `script/arxiv-dev-server 1707.08901`
