### ISSUE TITLE
Docker build not working

### ISSUE THREAD

**Issue by turian** [arxiv-vanity/engrafo#1079]
I just pulled main and ran `script/docker-build` but got the following error.

```
#6 7.307 Reading package lists...
#6 10.61 Building dependency tree...
#6 11.22 Reading state information...
#6 11.36 Package python-minimal is not available, but is referred to by another package.
#6 11.36 This may mean that the package is missing, has been obsoleted, or
#6 11.36 is only available from another source
#6 11.36 However the following packages replace it:
#6 11.36   python2-minimal
#6 11.36
#6 11.74 E: Package 'python-minimal' has no installation candidate
```

**Comment by bfirsh** [comment]
Ah, sorry, looks like the Docker image is broken. I haven't got time to fix right now, but open to contributions!

This is a pre-built one which you might be able to use: `arxivvanity/engrafo:latest`

**Comment by bfirsh** [comment]
Ah -- hello @turian. :)

Fixed this in the end -- thanks for the report. What were you trying to do with engrafo, out of interest?
