### ISSUE TITLE
Planned support for older papers without Arxiv IDs

### ISSUE THREAD

**Issue by tylerhou** [arxiv-vanity/engrafo#158]
Some papers (https://arxiv.org/abs/math/0209332) which are older don't have arxiv ID numbers. (In this particular case it doesn't have a LaTeX source as well, but there probably exist papers which are older that do. Is there planned support for them?

**Comment by bfirsh** [comment]
Yes! Tracking here: https://github.com/arxiv-vanity/arxiv-vanity/issues/69

Thanks for the report!
