### ISSUE TITLE
\ttfamily rendered in tex equations

### ISSUE THREAD

**Issue by zellyn** [arxiv-vanity/engrafo#162]
See https://www.arxiv-vanity.com/papers/1710.07600v1/ and search for `(2)`. You'll see `	
\ttfamily{minimize}`.

**Comment by bfirsh** [comment]
Thanks for the report!

**Comment by davidar** [comment]
This appears to have been fixed?

**Comment by bfirsh** [comment]
Yep thank you! Although that paper is pretty borked because of lack of support for proofs. :(
