### ISSUE TITLE
Unsupported use of \hfil

### ISSUE THREAD

**Issue by lingxz** [arxiv-vanity/engrafo#167]
e.g. https://www.arxiv-vanity.com/papers/0809.1819/

**Comment by bfirsh** [comment]
Thanks for the report!

**Comment by pkra** [comment]
Just touching base from the MathJax end. The arXiv content naturally contains a lot of cray TeX hacks like this. MathJax cannot support every TeX (or even LaTeX) math mode expression (ultimately, only a full TeX implementation can do that at which point your stuck in a print layout engine again).

**Comment by bfirsh** [comment]
@pkra hello! Thanks for mathjax! It’s been working brilliantly for us.

We’ve been using a series of hacks to make as much stuff work as possible: https://github.com/arxiv-vanity/engrafo/blob/master/src/math.js

We’d like to contribute back where appropriate though. Where do you draw the line between a hack and something you’d like in mathjax?

**Comment by bfirsh** [comment]
@pkra nice okay. That all makes sense. 

Perhaps we can figure out what the most common unsupported packages used are, then implement them as extensions that other people can use. That seems like the most useful way to contribute back. 

/cc @andreasjansson

**Comment by pkra** [comment]
> Perhaps we can figure out what the most common unsupported packages used are, then implement them as extensions that other people can use. That seems like the most useful way to contribute back.

Yes, that would be extremely useful information! And you don't have to implement them all by yourself -- drop a line to mathjax-users@googlegroups.com to check if others have interest or even worked on these.

**Comment by bfirsh** [comment]
Nice, thanks!

**Comment by bfirsh** [comment]
This seems to be fixed after switch to latexml. Seems like latexml implements the package for us, converting it into something that mathjax knows how to handle.
