### ISSUE TITLE
URL converter isn’t matching some TLDs

### ISSUE THREAD

**Issue by bfirsh** [arxiv-vanity/engrafo#174]
E.g. .gl https://github.com/arxiv-vanity/arxiv-vanity/issues/81

**Comment by zchenry** [comment]
I could not reproduce this locally.
I git cloned the latest repository and followed the docker setup steps in the readme file.
My OS is macOS High Sierra 10.13 and my docker version is `Docker version 17.09.0-ce, build afdb6d4`.

I downloaded the source file from the arxiv.
The locally generated html generated the correct url.

Also, 'gl' is matched in the file https://github.com/arxiv-vanity/engrafo/blob/master/pandocfilter/engrafo_pandocfilter/links.py.

**Comment by bfirsh** [comment]
Ah, looks like this was fixed but the render was out of date. I've re-rendered it and it's fixed.

Perhaps we should be more aggressive about re-rendering papers. Currently they get re-rendered every 30 days, but we could lower that to 7 days or something.

Thanks for investigating!

**Comment by zchenry** [comment]
Thank you for your quick response!
