### ISSUE TITLE
Possible to run without docker?

### ISSUE THREAD

**Issue by Naereen** [arxiv-vanity/engrafo#178]
Hi,
Is there any (easy) way to run engrafo *without* using docker?
Thanks in advance, and congratulations for this nice project!

**Comment by bfirsh** [comment]
No, no easy way. The closest thing is to run the commands in `Dockerfile` on a Linux machine. Good luck!

Out of interest - what is your reason for not wanting to use Docker?

**Comment by Naereen** [comment]
Hi @bfirsh, thanks for your quick reply.
OK, no issue, I will try and let you know if it works.

I have no reason to not use Docker, as well as no reason to want to use it. The main reason of my question is curiosity. It seems odd that a great piece of software, based on other open-source projects, require a container system like Docker to run.

Anyway, I will try what you suggested, and I see no reason for this to fail. Thanks!

**Comment by Naereen** [comment]
Oh, actually I just remember why I hated docker the first time I tried to use it. So many downloads just to try a small project! About 1.8 Go to test engrafo seems unreasonable (but it's not your fault).

**Comment by bfirsh** [comment]
Yeah - that's texlive! You'd be installing that much even if you used a local package manager...
