### ISSUE TITLE
Bibtex file not correctly used when generating a html article

### ISSUE THREAD

**Issue by Naereen** [arxiv-vanity/engrafo#183]
Hi again,
Launching `--help` from the engrafo docker image does not show any command to specify a bibtex file or force the inclusion of bibtex and correct the citations.
The resulting file is fine, except all the citations are `[?]` (but the PDF generated from `pdflatex && pdflatex && bibtex && pdflatex && pdflatex` is fine).
Any suggestions?

**Comment by bfirsh** [comment]
Known issue: https://github.com/arxiv-vanity/engrafo/issues/139

Thanks for the report!
