### ISSUE TITLE
Preserve \tag{}

### ISSUE THREAD

**Issue by gauss256** [arxiv-vanity/engrafo#189]
Sometimes you want to give an equation a specific number, for example because you are writing notes about a paper and want to use the same number as in the paper.

But if you use the markup `\tag` in your TeX it generates an error because engrafo generates its own tags.

**Comment by bfirsh** [comment]
@gauss256 Pretty sure this will work now we've switched to LaTeXML. Feel free to reopen if it is still an issue. :)
