### ISSUE TITLE
Implement subcaption package

### ISSUE THREAD

**Issue by bfirsh** [arxiv-vanity/engrafo#245]
- [ ] http://localhost:8010/html/1709.10478/
- [ ] https://www.arxiv-vanity.com/papers/1704.00717v2/
- [ ] https://www.arxiv-vanity.com/papers/1611.01957v3/

**Comment by dginev** [comment]
Independently requested in LaTeXML, seems popular, cross-referencing here

https://github.com/brucemiller/LaTeXML/issues/943
