### ISSUE TITLE
Improve styling of citet/citep

### ISSUE THREAD

**Issue by bfirsh** [arxiv-vanity/engrafo#249]
At the moment we are just naively applying the Distill styles to these, but they look terrible.

One option is to just remove them entirely, but often it is assumed the text is there in the prose. "In Bloggs (2014) it is shown..." would convert to "In [4] it is shown..." which reads a bit odd.

So, I think the best option is to just style them better, so they're inline in the text, but perhaps in a different colour to indicate that they're a reference and not just a link.

E.g.
 * https://www.arxiv-vanity.com/papers/1706.05137/

**Comment by jilljenn** [comment]
May consider `\autocite` as well: https://www.arxiv-vanity.com/papers/1709.01584/
Am I on the right issue, or should I create a new one?

**Comment by bfirsh** [comment]
Fixed in new design
