### ISSUE TITLE
span class ltx_ERROR_undefined found in a google paper

### ISSUE THREAD

**Issue by aranciokov** [arxiv-vanity/engrafo#256]
While checking a paper (https://www.arxiv-vanity.com/papers/1712.01208v1/) on your website I noticed there was a problem within it. 
![pic](https://user-images.githubusercontent.com/18611292/33850360-ea5859c4-deb3-11e7-9722-5f089b41a94a.PNG)
Checking the source code of the red part, I found this

`<span class="ltx_ERROR undefined">{algorithm}</span><span class="ltx_ERROR undefined">\LinesNumbered</span><span class="ltx_ERROR undefined">\AlgoDisplayBlockMarkers</span><span class="ltx_ERROR undefined">\SetAlgoBlockMarkers</span><span class="ltx_ERROR undefined">\SetAlgoNoEnd</span><span class="ltx_ERROR undefined">\SetAlgoLined</span><span class="ltx_ERROR undefined">\KwIn</span>`

**Comment by bfirsh** [comment]
This is because we don’t support algorithms yet. #26 

Thanks for the report!
