### ISSUE TITLE
Add support for cleveref

### ISSUE THREAD

**Issue by cogumbreiro** [arxiv-vanity/engrafo#266]
It would be great to add support for cleveref, currently a reference `\cref{ex:1}` yields `<span class="ltx_ERROR undefined">\cref</span>ex:1`.

About [cleveref](https://ctan.org/pkg/cleveref?lang=en):
>  The pack­age en­hances LaTeX's cross-ref­er­enc­ing fea­tures, al­low­ing the for­mat of ref­er­ences to be de­ter­mined au­to­mat­i­cally ac­cord­ing to the type of ref­er­ence. The for­mats used may be cus­tomised in the pream­ble of a doc­u­ment; ba­bel sup­port is avail­able (though the choice of lan­guages re­mains lim­ited: cur­rently Dan­ish, Dutch, English, French, Ger­man, Ital­ian, Nor­we­gian, Rus­sian, Span­ish and Ukra­nian).

> The pack­age also of­fers a means of ref­er­enc­ing a list of ref­er­ences, each for­mat­ted ac­cord­ing to its type. In such lists, it can col­lapse se­quences of nu­mer­i­cally-con­sec­u­tive la­bels to a ref­er­ence range. 

This issue is related to: brucemiller/LaTeXML#822

**Comment by bfirsh** [comment]
Fixed upstream, and added a test in engrafo. Thanks for the report!
