### ISSUE TITLE
Some papers failed to render in arxiv-vanity need  "Report this paper" or similar button?

### ISSUE THREAD

**Issue by potholiday** [arxiv-vanity/engrafo#305]
Some papers fail to render in arxiv-vanity https://www.arxiv-vanity.com/papers/1803.10122/ . I had also come across some other papers which dosen't render in arxiv-vanity. A `Report this paper` or similar button in arxiv-vanity itself would help to bring attention to such papers.

**Comment by bfirsh** [comment]
We already have that. ;)

It only works on desktop - perhaps you aren't seeing it because you're on a phone.
