### ISSUE TITLE
Support Quantum journal class

### ISSUE THREAD

**Issue by bfirsh** [arxiv-vanity/engrafo#316]
E.g. https://www.arxiv-vanity.com/papers/1708.00137/

They want to link to our papers but can't because we don't support their class.

**Comment by cgogolin** [comment]
Cool! Can you let me know once this works on the production system https://www.arxiv-vanity.com/ ?

**Comment by bfirsh** [comment]
@cgogolin ah, hello! Just sent you an email. ;)

**Comment by brucemiller** [comment]
The vanity version of the test paper is missing the references. Is that to be expected? (latexml bug or otherwise? I haven't tracked down the article source to see how the references were done).

**Comment by bfirsh** [comment]
Yes, that is weird, but expected. I think it is due to an old version of LaTeXML being used on there. It works fine in Engrafo master and LaTeXML master.

It’s just plain `thebibliography` and `bibitem` IIRC.
