### ISSUE TITLE
Link to the LaTeXML homepage in README.md is down

### ISSUE THREAD

**Issue by a3nm** [arxiv-vanity/engrafo#577]
The link to https://dlmf.nist.gov/LaTeXML/ in the README.md file is not working: "Sorry, but due to fact that the federal government is currently shut down, the website dlmf.nist.gov will be unavailable until further notice."

**Comment by bfirsh** [comment]
Fixed by congress.

**Comment by bfirsh** [comment]
Actually it was the air traffic controllers wasn't it?
