### ISSUE TITLE
Auto-QA

### ISSUE THREAD

**Issue by andreasjansson** [arxiv-vanity/engrafo#71]
We should automatically check a bunch (200?) papers to make sure a) we're not missing glaring holes, and b) fix the most important bugs first.

Assert present:
* Title
* Authors
* References

Assert absent:
* Red rendered unexpanded macros in math: http://localhost:8010/html/1707.08423v1/
* Unparsed MathJax (`<merror>` in the mathjax generated xml): http://localhost:8010/html/1312.6114v10/

What else?

**Comment by bfirsh** [comment]
Pretty much covered by #422!
